const TermsCondition = () => {
  return (
    <section>
      <div className="flex flex-col justify-center items-center h-48 bg-[#F9F9F9]">
        <h1 className="text-3xl text-dark-blue font-bold">
          Terms and Conditions{' '}
        </h1>
      </div>

      <div className="grid grid-cols-1 gap-8 py-12 lg:px-24">
        <div className="mb-4">
          <h3 className="font-bold text-[40px] text-[#242424]">Introduction</h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            This document is an electronic record under the UK&apos;s Electronic
            Communications Act and related regulations. This electronic record
            is generated by a computer system and does not require any physical
            or digital signatures.
          </p>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            Your use of the https://jenari.co.uk website and associated tools is
            governed by the following terms and conditions as applicable to
            Jenari.co.uk. By using the website, you agree to these terms,
            forming a binding contract with Arijenn Limited.
          </p>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            For the purposes of these terms, ‘You’ or ‘User’ refers to any
            individual or entity that has accepted this agreement to become a
            member of the website or makes transactions through the site. The
            terms &apos;We,&apos; &apos;Us,&apos; and &apos;Our&apos; refer to
            Arijenn Limited, registered in England.
          </p>
        </div>

        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            1. Membership Eligibility
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            Only individuals able to form legally binding contracts under UK law
            may register on or use Jenari.co.uk. If you are under 18, you must
            have a legal guardian or parent register on your behalf. We reserve
            the right to terminate your membership and refuse access if
            eligibility requirements are not met.
          </p>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            2. Account and Registration Obligations
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            You are responsible for maintaining the confidentiality of your user
            ID and password and for all activities under your account. If you
            provide false or outdated information, we reserve the right to
            suspend or terminate your account.
          </p>
        </div>

        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            3. Communications
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            By using Jenari.co.uk or contacting us electronically, you consent
            to receive electronic communications from us, including but not
            limited to email or other notices related to our services.
          </p>
        </div>

        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">4. Charges</h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            Membership on Jenari.co.uk is free, but we reserve the right to
            implement charges for certain services or modify existing fees.
            Changes to fees or policies will become effective immediately upon
            being posted on Jenari.co.uk.
          </p>
        </div>

        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            5. Use of the Site
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            Your use of Jenari.co.uk is subject to the following rules:
          </p>
          <div>
            <ul>
              <li className="pt-2 font-normal text-base text-[#626C7A]">
                - Do not upload or share content you do not own or have the
                right to share.
              </li>
              <li className="pt-2 font-normal text-base text-[#626C7A]">
                - Avoid content that is harmful, offensive, or illegal.
              </li>
              <li className="pt-2 font-normal text-base text-[#626C7A]">
                - Do not attempt to gain unauthorized access to the site or
                interfere with other users’ experience.
              </li>
              <li className="pt-2 font-normal text-base text-[#626C7A]">
                - Refrain from using automated tools or engaging in any
                activities that place excessive load on our servers.We reserve
                the right to monitor user activity and to remove any content
                that violates these terms.
              </li>
            </ul>
          </div>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            6. Contents Posted on Site
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            All material on Jenari.co.uk, including text, images, logos, and
            graphics, is protected by intellectual property laws and may not be
            reproduced or distributed without our express written consent.
          </p>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            7. Links to Other Sites
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            Jenari.co.uk may contain links to third-party websites. We are not
            responsible for the content or practices of these websites, and such
            links do not imply our endorsement.
          </p>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">8. Privacy</h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            We value your privacy. Please refer to our Privacy Policy for
            details on how we collect and handle your information.
          </p>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            9. Product Descriptions and Pricing
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            We strive for accuracy in product descriptions and pricing but
            cannot guarantee error-free information. In cases of errors, we
            reserve the right to rectify them or cancel orders as necessary.
          </p>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            10. Payments
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            All payments on Jenari.co.uk must be made in GBP (British Pounds).
            We are not responsible for issues arising from currency exchange or
            payment limitations set by your financial institution.
          </p>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            11. Cancellation of Orders
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            Jenari.co.uk reserves the right to cancel orders if we cannot meet
            the requested requirements or for other reasons outlined in these
            terms. Users will be informed of cancellations in a timely manner,
            and applicable refunds will be processed.
          </p>
        </div>
        <div className="mb-4">
          <h3 className="font-medium text-[28px] text-[#242424]">
            12. Limitation of Liability
          </h3>
          <p className="pt-2 font-normal text-base text-[#626C7A]">
            Jenari.co.uk is provided on an &quot;as-is&quot; basis, and Arijenn
            Limited will not be liable for damages arising from your use of the
            site or related services.
          </p>
        </div>
      </div>
    </section>
  );
};

export default TermsCondition;
